#!/usr/bin/env python3
"""Documentation-only: explain the rigorous test-retest reliability test that this
pipeline does NOT currently support, so the proxy results above are read with the
right caveat.

This script writes a structured note explaining:
  - What the rigorous (per-edge ICC) check would compute
  - What data it requires (HCP retest scans, n ≈ 45)
  - Why we're using the proxy (no retest pipeline wired)
  - What it would take to add the rigorous check later
"""
print("=" * 72)
print("RIGOROUS RELIABILITY CHECK — NOT RUN (no retest data in this pipeline)")
print("=" * 72)
print()
print("The proxy checks (proxy1_strength, proxy2_distance,")
print("decisive_partialled_enrichment) use edge weight and inter-region distance as")
print("STAND-INS for tractography reliability. Standard fallbacks in the field when")
print("retest data is unavailable.")
print()
print("The RIGOROUS version requires HCP test-retest data: ~45 subjects who were")
print("scanned twice with the same protocol. Per-edge reliability is then:")
print()
print("    edge_reliability[e] = ICC( SC_session1[:, e] ,  SC_session2[:, e] )")
print()
print("or, slightly weaker but acceptable:")
print()
print("    edge_reliability[e] = pearson_r( SC_session1[:, e] ,  SC_session2[:, e] )")
print()
print("computed across the 45 retest subjects. High ICC = edge measured consistently;")
print("low ICC = noise. This 64,620-dim reliability vector is the gold standard.")
print()
print("Then the same partialled-enrichment test in decisive_partialled_enrichment.py")
print("would be re-run with edge_reliability replacing the [strength, distance] proxy.")
print()
print("Why we are NOT running this here:")
print("  1. HCP retest connectomes are not in this project's preprocessed cache")
print("     (DEFAULT_CONN2CONN_CACHE_ROOT contains only the n=957 main-scan cohort).")
print("  2. The retest cohort would need separate ingestion: ~45 subjects, both")
print("     sessions, same parcellation, same SC pipeline (MRtrix/iFOD2/SIFT2 or")
print("     whatever was used for the main cohort), then per-edge ICC computation.")
print("  3. That is a 1-2 day pipeline-extension task, not a 1-hour check.")
print()
print("What it would take to add later, in rough order:")
print("  - Locate HCP retest dMRI on the storage (HCP-YA test-retest release).")
print("  - Run the same tractography pipeline used for the main cohort.")
print("  - Parcellate with Glasser (same atlas instance).")
print("  - Vectorize to 64,620 upper-triangle edges per session per subject.")
print("  - For each edge, compute ICC(2,1) across subjects between the two sessions.")
print("  - Save as data/atlas_info/sc_edge_reliability_glasser.npy (or similar).")
print("  - Re-run decisive_partialled_enrichment.py with edge_reliability in place")
print("    of [strength, distance].")
print()
print("CURRENT STATUS: proxy version only. Interpret findings.md accordingly — strong")
print("survival under proxy partialling is encouraging but does not fully rule out the")
print("reliability confound. Weak/no survival is a robust negative regardless of which")
print("reliability measure you use (proxy and retest typically agree on which edges")
print("are unreliable).")
